In [3]:
import pandas as pd
from Perceptron import Perceptron
from Ultilities import make_label

In [4]:
data = pd.read_csv("iris.data", header=None)

In [5]:
data.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [6]:
label = data.iloc[:,-1].unique()

In [7]:
data[4] = data.apply(lambda x: make_label(x[4], label), axis=1)

In [8]:
data.iloc[1,][4]

0.0

In [9]:
data = data.sample(frac=1, random_state=12).reset_index(drop=True)

In [10]:
X = data.iloc[:,0:4]
y= data.iloc[:, -1]

In [11]:
X = X.to_numpy()
y = y.to_numpy()

In [12]:
model = Perceptron()

In [13]:
model.fit(X, y)

28.47s - Error inserting pydevd breaks.
Traceback (most recent call last):
  File "c:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\debugpy\_vendored\pydevd\_pydevd_frame_eval\pydevd_modify_bytecode.py", line 328, in insert_pydevd_breaks
    for new_instruction in get_instructions_to_add(
  File "c:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\debugpy\_vendored\pydevd\_pydevd_frame_eval\pydevd_modify_bytecode.py", line 102, in get_instructions_to_add
    Instr("LOAD_CONST", _pydev_stop_at_break, lineno=stop_at_line - 1),
  File "c:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\debugpy\_vendored\pydevd\_pydevd_frame_eval\vendored\bytecode\instr.py", line 171, in __init__
    self._set(name, arg, lineno)
  File "c:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\debugpy\_vendored\pydevd\_pydevd_frame_eval\vendored\bytecode\instr.py", line 239, in _set
    _check_line

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
data1= data.head(5)

In [20]:
import numpy as np
np.zeros(4).reshape(())

ValueError: cannot reshape array of size 4 into shape (0,)

In [ ]:
for x in x1:
    print (x, type(x))

[5.  3.5 1.3 0.3] <class 'numpy.ndarray'>
[6.3 2.5 5.  1.9] <class 'numpy.ndarray'>
[4.4 3.  1.3 0.2] <class 'numpy.ndarray'>
[5.7 2.8 4.1 1.3] <class 'numpy.ndarray'>
[6.8 3.2 5.9 2.3] <class 'numpy.ndarray'>
