In [1]:
import pandas as pd
import numpy as np
from Perceptron import Perceptron
from Ultilities import make_binarylabel
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv("iris.data", header=None)
data.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [3]:
label = data.iloc[:,-1].unique()[1]
data[4] = data.apply(lambda x: make_binarylabel(x[4], label), axis=1)
data.iloc[1,][4]
data = data.sample(frac=1, random_state=12).reset_index(drop=True)
X = data.iloc[:,0:4]
y= data.iloc[:, -1]
X = X.to_numpy()
y = y.to_numpy()

In [4]:
label

'Iris-versicolor'

In [5]:
train = 0.7
val = 0.1
test = 0.2
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=test, random_state=42)

In [6]:
X_train.shape

(120, 4)

In [7]:
model = Perceptron(i = 10)

In [8]:
model.fit(X_train, y_train)

In [9]:
model.predict(X_test[29])

[5.1 3.5 1.4 0.3]


array([[1]])

In [10]:
y_pred = np.array([])


In [11]:
for x in X_test:
    pred = model.predict(x)
    y_pred = np.append(y_pred, pred)

[7.9 3.8 6.4 2. ]
[4.6 3.4 1.4 0.3]
[5.8 2.7 5.1 1.9]
[7.7 2.8 6.7 2. ]
[5.7 3.8 1.7 0.3]
[5.5 2.4 3.7 1. ]
[5.8 2.8 5.1 2.4]
[6.9 3.1 5.1 2.3]
[5.  2.3 3.3 1. ]
[4.7 3.2 1.6 0.2]
[7.2 3.  5.8 1.6]
[5.4 3.4 1.5 0.4]
[5.6 2.9 3.6 1.3]
[5.1 3.3 1.7 0.5]
[6.3 2.5 4.9 1.5]
[5.8 2.6 4.  1.2]
[5.9 3.  5.1 1.8]
[6.  2.7 5.1 1.6]
[6.4 2.7 5.3 1.9]
[5.  3.2 1.2 0.2]
[4.5 2.3 1.3 0.3]
[7.2 3.6 6.1 2.5]
[6.7 3.  5.  1.7]
[6.3 2.7 4.9 1.8]
[6.3 3.3 6.  2.5]
[6.8 2.8 4.8 1.4]
[6.7 3.1 4.4 1.4]
[5.  3.3 1.4 0.2]
[5.4 3.7 1.5 0.2]
[5.1 3.5 1.4 0.3]


In [13]:
pred = lambda x: model.predict(x)
def predict(X):
    return pred(X)

In [16]:
X_test[0].shape

(4,)

In [ ]:
y_test

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1], dtype=int64)

In [ ]:
accuracy_score(y_pred, y_test)

0.6